// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParcelTracking.Api.Data;

#nullable disable

namespace ParcelTracking.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250929135452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParcelTracking.Core.Models.Parcel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TrackingNumber")
                        .IsUnique();

                    b.ToTable("Parcels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a210a62d-6896-4884-915c-7c641921b9bf"),
                            CreatedAt = new DateTime(2025, 9, 29, 13, 54, 52, 247, DateTimeKind.Utc).AddTicks(3331),
                            Status = "In Transit",
                            TrackingNumber = "TRK001",
                            UpdatedAt = new DateTime(2025, 9, 29, 13, 54, 52, 247, DateTimeKind.Utc).AddTicks(3514)
                        },
                        new
                        {
                            Id = new Guid("5655145f-0137-438f-9152-44924c521402"),
                            CreatedAt = new DateTime(2025, 9, 28, 13, 54, 52, 247, DateTimeKind.Utc).AddTicks(3701),
                            Status = "Delivered",
                            TrackingNumber = "TRK002",
                            UpdatedAt = new DateTime(2025, 9, 29, 11, 54, 52, 247, DateTimeKind.Utc).AddTicks(3776)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
