name: Build and Deploy Parcel Tracking

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Nightly build at 2 AM UTC
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_API: ${{ github.repository }}/api
  IMAGE_NAME_WEB: ${{ github.repository }}/web

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          **/bin/Release/**
          **/obj/Release/**
        retention-days: 1

  build-and-push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'release' && github.event.action == 'published'


    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check for Docker files
      id: docker-check
      run: |
        if [ -f "./ParcelTracking.Api/Dockerfile" ]; then
          echo "api_dockerfile_exists=true" >> $GITHUB_OUTPUT
        else
          echo "api_dockerfile_exists=false" >> $GITHUB_OUTPUT
          echo "⚠️ API Dockerfile not found at ./ParcelTracking.Api/Dockerfile"
        fi
        if [ -f "./ParcelTracking.Web/Dockerfile" ]; then
          echo "web_dockerfile_exists=true" >> $GITHUB_OUTPUT
        else
          echo "web_dockerfile_exists=false" >> $GITHUB_OUTPUT
          echo "⚠️ Web Dockerfile not found at ./ParcelTracking.Web/Dockerfile"
        fi

    - name: Set up Docker Buildx
      if: steps.docker-check.outputs.api_dockerfile_exists == 'true' || steps.docker-check.outputs.web_dockerfile_exists == 'true'
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      if: steps.docker-check.outputs.api_dockerfile_exists == 'true' || steps.docker-check.outputs.web_dockerfile_exists == 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for API
      if: steps.docker-check.outputs.api_dockerfile_exists == 'true'
      id: meta-api
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_API }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Extract metadata for Web
      if: steps.docker-check.outputs.web_dockerfile_exists == 'true'
      id: meta-web
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEB }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push API image
      if: steps.docker-check.outputs.api_dockerfile_exists == 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./ParcelTracking.Api/Dockerfile
        # Only push to registry on main branch, build only on PRs
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: ${{ steps.meta-api.outputs.tags }}
        labels: ${{ steps.meta-api.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Web image
      if: steps.docker-check.outputs.web_dockerfile_exists == 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./ParcelTracking.Web/Dockerfile
        # Only push to registry on main branch, build only on PRs
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: ${{ steps.meta-web.outputs.tags }}
        labels: ${{ steps.meta-web.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Report Docker build status
      run: |
        echo "🏗️ Docker Build Summary:"
        if [ "${{ steps.docker-check.outputs.api_dockerfile_exists }}" == "true" ]; then
          echo "✅ API Docker image processing completed"
        else
          echo "⏭️ API Docker image skipped (Dockerfile not found)"
        fi
        if [ "${{ steps.docker-check.outputs.web_dockerfile_exists }}" == "true" ]; then
          echo "✅ Web Docker image processing completed"
        else
          echo "⏭️ Web Docker image skipped (Dockerfile not found)"
        fi

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build-and-push-images
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Check for Docker files and previous job status
      id: scan-check
      run: |
        if [ -f "./ParcelTracking.Api/Dockerfile" ]; then
          echo "api_dockerfile_exists=true" >> $GITHUB_OUTPUT
        else
          echo "api_dockerfile_exists=false" >> $GITHUB_OUTPUT
          echo "⚠️ API Dockerfile not found, skipping API security scan"
        fi
        if [ -f "./ParcelTracking.Web/Dockerfile" ]; then
          echo "web_dockerfile_exists=true" >> $GITHUB_OUTPUT
        else
          echo "web_dockerfile_exists=false" >> $GITHUB_OUTPUT
          echo "⚠️ Web Dockerfile not found, skipping Web security scan"
        fi
        
        # Check if we should run any scans
        if [ "${{ env.api_dockerfile_exists }}" == "true" ] || [ "${{ env.web_dockerfile_exists }}" == "true" ]; then
          echo "should_run_scans=true" >> $GITHUB_OUTPUT
        else
          echo "should_run_scans=false" >> $GITHUB_OUTPUT
          echo "ℹ️ No Docker files found, security scan will be skipped"
        fi
      
    # For PRs, scan the built images locally; for main branch, scan pushed images
    - name: Build API image for scanning (PR only)
      if: github.event_name == 'pull_request' && steps.scan-check.outputs.api_dockerfile_exists == 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./ParcelTracking.Api/Dockerfile
        push: false
        tags: local-api:latest
        load: true

    - name: Build Web image for scanning (PR only)
      if: github.event_name == 'pull_request' && steps.scan-check.outputs.web_dockerfile_exists == 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./ParcelTracking.Web/Dockerfile
        push: false
        tags: local-web:latest
        load: true

    - name: Run Trivy vulnerability scanner for API
      if: steps.scan-check.outputs.api_dockerfile_exists == 'true'
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ github.event_name == 'pull_request' && 'local-api:latest' || format('{0}/{1}:latest', env.REGISTRY, env.IMAGE_NAME_API) }}
        format: 'sarif'
        output: 'api-trivy-results.sarif'

    - name: Run Trivy vulnerability scanner for Web
      if: steps.scan-check.outputs.web_dockerfile_exists == 'true'
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ github.event_name == 'pull_request' && 'local-web:latest' || format('{0}/{1}:latest', env.REGISTRY, env.IMAGE_NAME_WEB) }}
        format: 'sarif'
        output: 'web-trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      if: steps.scan-check.outputs.api_dockerfile_exists == 'true' || steps.scan-check.outputs.web_dockerfile_exists == 'true'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: '.'
        
    - name: Report security scan status
      run: |
        echo "🔒 Security Scan Summary:"
        if [ "${{ steps.scan-check.outputs.api_dockerfile_exists }}" == "true" ]; then
          echo "✅ API security scan completed"
        else
          echo "⏭️ API security scan skipped (Dockerfile not found)"
        fi
        if [ "${{ steps.scan-check.outputs.web_dockerfile_exists }}" == "true" ]; then
          echo "✅ Web security scan completed"
        else
          echo "⏭️ Web security scan skipped (Dockerfile not found)"
        fi

  deployment-notification:
    name: Deployment Notification
    runs-on: ubuntu-latest
    needs: [build-and-push-images, security-scan]
    if: always() && github.event_name == 'release' && github.event.action == 'published'

    steps:
    - name: Notify status
      run: |
        echo "📋 Workflow Summary Report:"
        echo "Event: ${{ github.event_name }}"
        echo "Branch: ${{ github.ref_name }}"
        echo ""
        
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "🔄 Pull Request Workflow Results:"
          echo "Build & Test: ${{ needs.build-and-push-images.result }}"
          echo "Docker Images: ${{ needs.build-and-push-images.result }}"
          echo "Security Scan: ${{ needs.security-scan.result }}"
          echo ""
          
          if [ "${{ needs.build-and-push-images.result }}" == "success" ]; then
            echo "✅ Docker images processed successfully (not pushed to registry)"
          else
            echo "❌ Docker image processing had issues"
          fi
          
          if [ "${{ needs.security-scan.result }}" == "success" ]; then
            echo "✅ Security scanning completed"
          else
            echo "⚠️ Security scanning encountered issues or was skipped"
          fi
        else
          echo "🚀 Main Branch Deployment:"
          if [ "${{ needs.build-and-push-images.result }}" == "success" ] && [ "${{ needs.security-scan.result }}" == "success" ]; then
            echo "✅ Full pipeline completed successfully"
            echo "🚀 Images available at:"
            echo "   - API: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_API }}:latest"
            echo "   - Web: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEB }}:latest"
          else
            echo "⚠️ Pipeline completed with warnings or failures:"
            echo "   - Docker Build: ${{ needs.build-and-push-images.result }}"
            echo "   - Security Scan: ${{ needs.security-scan.result }}"
          fi
        fi